spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pbl?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: Saw2@leaf31!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    serialization:
      indent-output: true
  data:
    redis:
      host: localhost
      port: 6379


spring.config.import: optional:application-secret.yml
