spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pbl?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: sichuka5767@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    serialization:
      indent-output: true
  data:
    redis:
      host: localhost
      port: 6379


server:
  port: 8080
